BP-619: Fix issues related to v15 migration regarding look & feel on table component
enigmatry/entry-angular-building-blocks pull request #129
Opened 2023-07-26 12:33 UTC by Cvetanovic

https://jira.enigmatry.com/browse/BP-619

2023-07-27 07:40 UTC, jovana-marceta commented on apps/demo-app/src/styles/modules/theming/_theming.scss
> +			infix-padding-top: .4375em,
@Cvetanovic  Is it possible to circle this to rounded number and replace it with px units?

2023-07-27 07:40 UTC, jovana-marceta commented on apps/demo-app/src/styles/partials/main.scss
>  @use '../modules/typography/fonts' as app_font;
@Cvetanovic  Is it possible to use kebab case instead of snake case when naming aliases?

2023-07-27 07:50 UTC, jovana-marceta commented on apps/demo-app/src/styles/partials/main.scss
>  @use '../modules/theming/theming' as app_theme;
Is it possible to use kebab case instead of snake case when naming aliases?

2023-08-07 15:04 UTC, typhoon41 requested changes

2023-08-11 20:04 UTC, typhoon41 commented on apps/demo-app/src/styles/modules/theming/_theming.scss
> +/* stylelint-disable number-max-precision */
Stylelint ignore not needed.

2023-08-11 20:05 UTC, typhoon41 commented on apps/demo-app/src/styles/partials/main.scss
> +@use '../modules/typography/fonts' as app-font;
Line 3 is not needed.

2023-08-11 20:08 UTC, typhoon41 requested changes

2023-08-11 20:08 UTC, typhoon41 commented on libs/entry-components/styles/modules/_default-theme.scss
> +				disabled-hover: 2px solid #EBEBEB,
Extra comma on the end is not needed.

2023-08-13 11:57 UTC, typhoon41 approved these changes

2023-08-13 11:57 UTC, merged