BP-955: Set background color for radio buttons
enigmatry/entry-angular-building-blocks pull request #195
Opened 2024-03-07 11:58 UTC by jovana-marceta

https://enigmatry.atlassian.net/browse/BP-955

2024-03-07 12:03 UTC, jovana-marceta commented on libs/entry-components/styles/modules/components/buttons/_radio.scss
> +					border-color: map.get($theme, 'general', 'buttons', 'radio', 'background') !important;
@typhoon41  Acknowledging that the use important is discouraged, I am unsatisfied with this approach and will seek a more suitable solution. One possibility is to increase specificity by introducing a custom class in the Formly generated files for radio buttons.

2024-03-14 14:39 UTC, Cvetanovic commented on libs/entry-components/styles/modules/components/buttons/_radio.scss
> +			&:not(:disabled):active .mdc-radio__native-control:enabled:checked + .mdc-radio__background .mdc-radio__outer-circle {
You have duplicated selectors. You can create variables for them and then you don't need ignore files in stylelint

2024-03-14 14:39 UTC, Cvetanovic commented on libs/entry-components/styles/modules/components/buttons/_radio.scss
> +			.mdc-radio__outer-circle, .mdc-radio__inner-circle {
duplicated selector

2024-03-14 14:39 UTC, Cvetanovic commented on libs/entry-components/styles/modules/components/buttons/_radio.scss
> +					border-color: map.get($theme, 'general', 'buttons', 'radio', 'background');
create variable for this map

2024-03-14 19:05 UTC, typhoon41 requested changes

2024-03-14 19:05 UTC, typhoon41 commented on libs/entry-components/styles/modules/components/buttons/_radio.scss
> +				border-color: map.get($theme, 'general', 'buttons', 'radio', 'background');
The same variable should be used on all places (eliminate duplication)

2024-03-14 19:05 UTC, typhoon41 commented on libs/entry-components/.stylelintrc.json
> +    "styles/modules/components/buttons/_radio.scss"
Why this?!

2024-03-15 12:02 UTC, jovana-marceta commented on libs/entry-components/.stylelintrc.json
> +    "styles/modules/components/buttons/_radio.scss"
I initially it to the stylelint ignore list because it generated five warnings, which I believed were too many to address directly in the file. However, upon further review, I realized that by using variables for selectors, I could effectively eliminate these warnings.

2024-03-15 18:46 UTC, typhoon41 commented on libs/entry-components/.stylelintrc.json
> +    "styles/modules/components/buttons/_radio.scss"
I understand, but we have hundreds of rules being applied on every single file. If we're gonna turn off remaining 100 rules just for sake of 5, half of the solution would end up in ignore section.

Ignore section should be used exclusively (temporarily) for legacy code we don't have budget to deal with, vendor libraries (we're not responsible for their code quality) and other types of classes we can't have full control over (i.e. code generation or some PoC work).

2024-03-15 18:48 UTC, typhoon41 approved these changes

2024-03-18 08:15 UTC, merged