BP-954: Set color and background for checkboxes
enigmatry/entry-angular-building-blocks pull request #196
Opened 2024-03-08 16:38 UTC by Cvetanovic

https://enigmatry.atlassian.net/browse/BP-954

2024-03-09 15:16 UTC, typhoon41 requested changes

2024-03-09 15:16 UTC, typhoon41 commented on libs/entry-components/styles/modules/_default-theme.scss
> +			border: null
Except for hovering effects, we're not changing border colors at all. I suggest changing this name to border-hover-color so we do not confuse anybody. If behavior changes, so will theme.

2024-03-09 15:16 UTC, typhoon41 commented on libs/entry-components/styles/modules/components/checkboxes/_generator.scss
> +	.mat-mdc-checkbox.mat-accent, .mat-mdc-checkbox.mat-primary {
If we're aware of the fact we wanna override behaviors of checkboxes, why would we put color="primary" or color="accent" on them?

2024-03-09 15:16 UTC, typhoon41 commented on libs/entry-components/styles/modules/components/checkboxes/_generator.scss
> +				.mdc-checkbox__native-control:enabled:not(:checked):not(:indeterminate):not([data-endeterminate = 'true']) ~ .mdc-checkbox__background, .mdc-checkbox__native-control:enabled:indeterminate ~ .mdc-
Selectors are duplicated here. Please extract them to a variable and use that var on both places.

2024-03-14 13:58 UTC, jovana-marceta commented on libs/entry-components/styles/modules/components/checkboxes/_generator.scss
> +	$background-color: map.get($theme, 'general', 'checkboxes', 'background');
Maybe we could consider renaming variable to $background since the context seems clear enough.

2024-03-14 18:34 UTC, typhoon41 approved these changes

2024-03-15 08:12 UTC, jovana-marceta approved these changes

2024-03-15 08:38 UTC, merged